version: '3.7'

services:
  ollama:
    image: ollama/ollama:0.20.3
    environment:
      #https://ollama.ai/library
      #MODEL: "mistral"
      #MODEL: "llama2-uncensored"
      #MODEL: "codellama"
      MODEL: "gemma4:e4b"
    volumes:
      - ./config/ollama:/root/config
      - ./data:/root/.ollama
    entrypoint: ["/bin/bash", "/root/config/start.sh"]
